source 'https://rubygems.org'

gem 'activesupport', require: 'active_support/all'
gem 'logger'
gem 'mysql2'
gem 'pry'
gem 'puma'
gem 'rack', '>= 2.0.6'
gem 'rack-parser', require: 'rack/parser'
gem 'racksh'
gem 'sequel'
gem 'sinatra'
gem 'sinatra-contrib', require: 'sinatra/reloader'
